package cart.products;

/**
 * Represents an electronic product (phones, laptops, headphones, etc.).
 *
 * OOP CONCEPTS DEMONSTRATED:
 *   - Inheritance    : extends Product, inheriting all core product behaviour
 *   - Polymorphism   : overrides getCategory() and getDetails() with Electronics-specific output
 *   - Encapsulation  : brand and warrantyMonths are private with public getters
 *   - Constructors   : two overloaded constructors matching Product's overload pattern
 *   - Method Override: getDetails() and toString() both overridden here
 */
public class Electronics extends Product {

    // Electronics-specific attributes
    private final String brand;
    private final int    warrantyMonths;  // manufacturer warranty in months

    // ------------------------------------------------------------------
    // Constructors  (Overloading: with explicit ID vs auto-generated ID)
    // ------------------------------------------------------------------

    /**
     * Full constructor — explicit product ID, suitable for pre-seeded catalog data.
     */
    public Electronics(int productId, String name, double price,
                       int stockQuantity, String brand, int warrantyMonths) {
        super(productId, name, price, stockQuantity); // calls Product(int, String, double, int)
        this.brand          = brand;
        this.warrantyMonths = warrantyMonths;
    }

    /**
     * Auto-ID constructor — ID is generated by the parent class.
     */
    public Electronics(String name, double price,
                       int stockQuantity, String brand, int warrantyMonths) {
        super(name, price, stockQuantity); // calls Product(String, double, int)
        this.brand          = brand;
        this.warrantyMonths = warrantyMonths;
    }

    // ------------------------------------------------------------------
    // Polymorphic method implementations  (Overriding abstract methods)
    // ------------------------------------------------------------------

    /**
     * Returns the category label for this type.
     * Runtime polymorphism: a Product reference holding an Electronics object
     * will return "Electronics" when getCategory() is called.
     */
    @Override
    public String getCategory() {
        return "Electronics";
    }

    /**
     * Returns Electronics-specific attributes formatted for display.
     * This is the key polymorphism demonstration: getDetails() on a List<Product>
     * will produce a different string depending on the concrete subclass type.
     */
    @Override
    public String getDetails() {
        return String.format("Brand: %-12s | Warranty: %d months", brand, warrantyMonths);
    }

    // ------------------------------------------------------------------
    // toString  (Overriding: extends parent's row with extra detail)
    // ------------------------------------------------------------------

    /**
     * Overrides Product.toString() to append Electronics-specific attributes.
     * Calls super.toString() to reuse the common formatting, then appends extra info.
     * This demonstrates chained method overriding.
     */
    @Override
    public String toString() {
        return super.toString() + "\n        " + getDetails();
    }

    // ------------------------------------------------------------------
    // Getters
    // ------------------------------------------------------------------
    public String getBrand()          { return brand; }
    public int    getWarrantyMonths() { return warrantyMonths; }
}
